CREATE TABLE [dbo].[Modelo](
	[ModeloID] [int] NOT NULL,
	[Marca] [varchar](12) NOT NULL,
	[Electrodomestico] [varchar](50) NOT NULL,
 CONSTRAINT [PK__modelo__FA6052BA1273C1CD] PRIMARY KEY CLUSTERED 
(
	[ModeloID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO